export const comments = [
  'Needs significant improve. Keep working on it!',
  'Below expectations. Try again with more effort.',
  'Not quite there yet. Keep practising and learning.',
  'Fair effort, but room for improvement. Keep pushing!',
  'Showing potential, but need more work. Stay focused!',
  'Getting closer, but still a bit off. Keep it up!',
  'Good try, but just shy of a pass. Keep going!',
  'Passing grade, but can do better. Keep improving!',
  'Average performance. Aim higher next time!',
  'Good effort, but can refine skills further. Keep it up!',
  'Solid performance! Building momentum, Keep going!',
  'Good job! Demonstrating a strong understanding.',
  'Excellent effort! Consistently delivering quality work.',
  'Outstanding performance! Showing mastery of skills.',
  'Impressive achievement! Exceeding expectations.',
  'Exception performance! Demonstrating expertise.',
  'Outstanding achievement! Showcasing mastery.',
  'Phenomenal work! Exceeding expectations',
  'Perfect score! Flawless performance',
];
